name: Build and Test

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: CI=false npm run build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test
  
  dockerize:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}


      - name: build with docker
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/react-app .

      - name: tag docker image
        run: docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/react-app ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:latest

      - name: push to docker hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:latest